version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/nestjs_db
    depends_on:
      - mongodb
    command: npm run start:dev

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
